[package]
name = "arrow_jmespath"
version = "1.0.0"
edition = "2021"

[dependencies]
arrow = "53.3.0"
arrow-json = "53.3.0"
arrow-array = "53.3.0"
arrow-schema = "53.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
nom = "7.1"
regex = "1.9"
